name: Benchmark_TTA
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.6.15=py38h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1q=h7f8727e_0
  - pip=22.1.2=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=63.4.1=py38h06a4308_0
  - sqlite=3.39.2=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - advertorch==0.2.3
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - art==5.8
    - asttokens==2.2.1
    - attrs==22.2.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.2
    - bleach==6.0.0
    - blessed==1.20.0
    - cffi==1.15.1
    - chardet==3.0.4
    - colorama==0.4.6
    - comm==0.1.2
    - contourpy==1.0.7
    - cycler==0.11.0
    - debugpy==1.6.6
    - decorator==5.1.1
    - defusedxml==0.7.1
    - device==0.1
    - executing==1.2.0
    - fastjsonschema==2.16.3
    - filelock==3.10.0
    - fonttools==4.38.0
    - fqdn==1.5.1
    - gdown==4.7.1
    - geotorch==0.3.0
    - gpustat==1.1
    - huggingface-hub==0.11.0rc0
    - idna==2.10
    - imageio==2.27.0
    - importlib-metadata==6.1.0
    - importlib-resources==5.12.0
    - iopath==0.1.8
    - ipykernel==6.21.3
    - ipython==8.11.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.4
    - isoduration==20.11.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-client==8.0.3
    - jupyter-console==6.6.3
    - jupyter-core==5.3.0
    - jupyter-events==0.6.3
    - jupyter-server==2.5.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.5
    - kiwisolver==1.4.4
    - littleutils==0.2.2
    - markupsafe==2.1.1
    - matplotlib==3.6.3
    - matplotlib-inline==0.1.6
    - matpotlib==0.0.1
    - mistune==2.0.5
    - nbclassic==0.5.3
    - nbclient==0.7.2
    - nbconvert==7.2.10
    - nbformat==5.7.3
    - nest-asyncio==1.5.6
    - notebook==6.5.3
    - notebook-shim==0.2.2
    - numpy==1.19.5
    - nvidia-ml-py==11.525.112
    - ogb==1.3.5
    - outdated==0.2.2
    - packaging==23.0
    - pandas==1.1.5
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.2.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.1.1
    - portalocker==2.5.1
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.38
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycm==3.8
    - pycparser==2.21
    - pygments==2.14.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytorch-adapt==0.0.83
    - pytorch-metric-learning==1.6.3
    - pytz==2022.2.1
    - pyyaml==6.0
    - pyzmq==25.0.1
    - qtconsole==5.4.1
    - qtpy==2.3.0
    - requests==2.0.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - seaborn==0.12.2
    - send2trash==1.8.0
    - six==1.16.0
    - sklearn==0.0.post1
    - sniffio==1.3.0
    - soupsieve==2.4
    - stack-data==0.6.2
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - timm==0.6.11
    - tinycss2==1.2.1
    - torch==1.12.1+cu113
    - torchaudio==0.12.1+cu113
    - torchdiffeq==0.2.3
    - torchmetrics==0.9.3
    - torchvision==0.13.1+cu113
    - tornado==6.2
    - tqdm==4.56.2
    - traitlets==5.9.0
    - typing-extensions==4.3.0
    - uri-template==1.2.0
    - urllib3==1.25.11
    - wcwidth==0.2.6
    - webcolors==1.12
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - widgetsnbextension==4.0.5
    - wilds==2.0.0
    - yacs==0.1.8
    - zipp==3.15.0
prefix: /home/yongcan.yu/anaconda3/envs/Benchmark_TTA
